# Generated by Django 4.1.2 on 2023-01-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrudOil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ExRateJPYKRW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ExRateUSDKRW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="GoldGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="GoldKorea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Kosdaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
                ("startvalue", models.FloatField()),
                ("highvalue", models.FloatField()),
                ("lowvalue", models.FloatField()),
                ("volume", models.FloatField()),
                ("tranactionvalue", models.BigIntegerField()),
                ("marketcap", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Kospi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
                ("startvalue", models.FloatField()),
                ("highvalue", models.FloatField()),
                ("lowvalue", models.FloatField()),
                ("volume", models.FloatField()),
                ("tranactionvalue", models.BigIntegerField()),
                ("marketcap", models.BigIntegerField()),
            ],
        ),
    ]
