# Generated by Django 4.1.2 on 2023-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jboard", "0002_rename_tranactionvalue_kosdaq_tranaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldkorea",
            name="highvalue",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldkorea",
            name="lowvalue",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goldkorea",
            name="startvalue",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
