# Generated by Django 4.1.2 on 2023-01-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jboard", "0003_goldkorea_highvalue_goldkorea_lowvalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExRateCNYKRW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ExRateEURKRW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("lastvalue", models.FloatField()),
                ("difference", models.FloatField()),
            ],
        ),
    ]
