# Generated by Django 4.1.2 on 2023-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jboard", "0005_kospi_diffrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="kosdaq",
            name="diffrate",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
