# Generated by Django 4.1.2 on 2023-01-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jboard", "0006_kosdaq_diffrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PFBonds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField()),
                ("buyprice", models.IntegerField()),
                ("buynum", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PFKstocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField()),
                ("buyprice", models.IntegerField()),
                ("buynum", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
